theme: jekyll-theme-minimal
markdown: kramdown
<script type="application/ld+json">
{"description":"Projects done while learning","url":"https://juhi2021.github.io/","@type":"WebSite","headline":"ğ—£ğ—¿ğ—¼ğ—·ğ—²ğ—°ğ˜ ğ—Ÿğ—¶ğ˜€ğ˜ ğ˜„ğ—¶ğ˜ğ—µ ğ—°ğ—¼ğ—±ğ—²","name":"Juhi Jain","@context":"https://schema.org"}</script>

